# Generated by Django 5.1.3 on 2026-07-05 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(max_length=60)),
                ('emoji', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True)),
                ('primary', models.CharField(max_length=7)),
                ('secondary', models.CharField(max_length=7)),
                ('userId', models.CharField(blank=True, max_length=120, null=True)),
                ('rating', models.FloatField(default=5.0)),
                ('followers', models.IntegerField(default=0)),
                ('isOpen', models.BooleanField(default=True)),
                ('windows', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
