# Generated by Django 5.1.3 on 2026-07-12 14:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='seguidores',
            field=models.ManyToManyField(blank=True, related_name='lojas_seguidas', to=settings.AUTH_USER_MODEL),
        ),
    ]
