# Generated by Django 5.1.3 on 2026-07-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0002_loja_seguidores'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='cor_primaria',
            field=models.CharField(default='#D85A30', max_length=20),
        ),
        migrations.AddField(
            model_name='loja',
            name='cor_secundaria',
            field=models.CharField(default='#FAF7F4', max_length=20),
        ),
        migrations.AddField(
            model_name='loja',
            name='emoji',
            field=models.CharField(default='🏪', max_length=10),
        ),
        migrations.AddField(
            model_name='loja',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loja',
            name='esta_aberta',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='loja',
            name='janelas',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='loja',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
