# Generated by Django 5.1.3 on 2026-07-12 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0003_loja_cor_primaria_loja_cor_secundaria_loja_emoji_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='emoji',
            field=models.CharField(default='📦', max_length=10),
        ),
    ]
