# Generated by Django 5.1.3 on 2026-07-25 22:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0005_alter_loja_dono'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='favoritado_por',
            field=models.ManyToManyField(blank=True, related_name='produtos_favoritos', to=settings.AUTH_USER_MODEL),
        ),
    ]
