# Generated by Django 5.1.3 on 2026-07-27 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunidade', '0002_postreacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='respondido_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='resposta_dono',
            field=models.TextField(blank=True, null=True),
        ),
    ]
